{{- $root := . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgres.fullname" $root }}-app
spec:
  selector:
    matchLabels:
      app: {{ include "postgres.fullname" $root }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ include "postgres.fullname" $root }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    spec:
      serviceAccountName: {{ include "postgres.fullname" $root }}
      containers:
        - name: {{ include "postgres.fullname" $root }}-app
          image: {{ if .Values.images.repository }}{{ printf "%s/" .Values.images.repository }}{{ end }}{{ .Values.images.tags }}
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "postgres.fullname" $root }}-secrets
          readinessProbe:
            tcpSocket:
              port: {{ .Values.network.service.port}}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.network.service.port}}
            initialDelaySeconds: 15
            periodSeconds: 20
            
